creating contract multisig proposal
use-inkubator/Ecosystem-Grants pull request #14
Opened 2023-05-03 12:52 UTC by mmunilla

2023-05-04 01:33 UTC, SotaWatanabe commented
Thank you very much for your application. I trust Protofile has been a great builder, and the team has already proven the capability via Gnosis Safe EVM implementation.

2023-05-04 14:06 UTC, SotaWatanabe commented
This is under the infra track of our program and Hang from Phala is in charge of the technical review. I will ping him and let him work on this. cc @TtomaS7

2023-05-09 08:03 UTC, mike1729 requested changes

2023-05-09 08:03 UTC, mike1729 commented on applications/ink_contract_multi-sig.md
> +We will initiate the project with a thorough Discovery & Proof of Concept phase. During this stage, we will delve into the existing implementations and explore how we can enhance their value. The pri
> This will enable us to evaluate the architecture and establish the feasibility of the project.
I believe this should be a part of the application process.

2023-05-09 13:15 UTC, mmunilla commented on applications/ink_contract_multi-sig.md
> +#### <a name="step1"></a>1.- Discovery & Proof of Concept (PoC) phase
updated proposal

2023-05-10 22:30 UTC, DoubleOTheven commented on applications/ink_contract_multi-sig.md
> +It is an essential tool for:
I agree!

2023-05-10 22:34 UTC, DoubleOTheven commented on applications/ink_contract_multi-sig.md
> +We have already implemented the Gnosis Safe multi-sig wallet in Astar. Still, that functionality has a narrow scope because is constrained to the EVM Pallet. So, we intend to bring similar functional
Gnosis is a great product. I like that you are very user-focused. The Polkadot ecosystem needs more of that.

2023-05-10 22:42 UTC, DoubleOTheven commented on applications/ink_contract_multi-sig.md
> +- Technology stack: Ink!, Rust, React, NextJS, TypeScript
For React, please take a look at [useink](https://github.com/paritytech/useink). There should be a major release in the next week or two. React Hooks for Wasm contracts

2023-05-10 22:44 UTC, DoubleOTheven commented on applications/ink_contract_multi-sig.md
> +| 1. | Figma file | We will deliver a UX/UI Design of the Multisig wallet user interface.|
Thank you for considering this

2023-05-10 22:45 UTC, DoubleOTheven approved these changes
I approve.

2023-05-10 23:53 UTC, SotaWatanabe commented
Voted yes

2023-05-11 04:58 UTC, SotaWatanabe approved these changes

2023-05-11 09:46 UTC, mike1729 commented on applications/ink_contract_multi-sig.md
> +#### <a name="step1"></a>1.- Discovery & Proof of Concept (PoC) phase
You've updated the proposal but you haven't specified which design you want to implement.

2023-05-11 09:48 UTC, mike1729 requested changes
The changes still don't include a proposal for a design of the underlying cryptographic scheme, please provide some overview what you actually want to implement. There are multiple designs for multisig that enables updating threshold and set of signers.

2023-05-11 14:55 UTC, GabrielCamba commented
> The changes still don't include a proposal for a design of the underlying cryptographic scheme, please provide some overview what you actually want to implement. There are multiple designs for multisig that enables updating threshold and set of signers.

Hello @mike1729 ! Thank you for your question. To clarify, our approach will primarily be based on the existing model of the Gnosis Safe multi-sig wallet, but optimized for the Substrate environment using the ink! smart contract language. At first, we are NOT going to include a backend, we will solve every interaction transparently settling it on-chain using the smart contract.

Here's a high-level overview of the intended multisig scheme:

Initialization: The multisig wallet is initialized with a set of owners and a threshold. Each owner represents an individual account, and the threshold represents the minimum number of approvals required to execute a transaction.

Approval Collection: When a transaction is proposed, it needs to be approved or rejected by a certain number of owners. Each owner sends an extrinsic to vote for or against executing a transaction. This process will be done on-chain, and the resulting approvals will increase a counter until the threshold is met.

Transaction Execution: Once the threshold number of approvals is reached, the extrinsic will be executed.

Owner Management: To handle the dynamic addition or removal of owners, we propose a mechanism similar to regular transaction approval. A proposal for adding or removing an owner is created, which requires the threshold number of approvals from existing owners. Once the required number is met, the change is executed.

As for the cryptographic scheme for the signatures, we will use the existing extrinsics signature that’s already implemented in polkadot and the contracts pallet.

Please note that this is a high-level overview and the exact design will be fleshed out during the Discovery & PoC phase of our project. We understand the importance of security and efficiency in the design of such a system and plan to devote considerable time and effort to ensure our solution meets these requirements. We appreciate your patience, and we expect this response meets your expectations and look forward to answering any further questions.

2023-05-15 15:17 UTC, mike1729 requested changes
I propose to split Milestone 1 -  Discovery & PoC into two milestones:
Milestone 1 - Specification that as a result has a specification of what you want to implement and you clearly specify which limitations of native multisig will be improved
Milestone 2 - PoC

2023-05-15 18:28 UTC, DiegoTorresborda commented
> I propose to split Milestone 1 - Discovery & PoC into two milestones: Milestone 1 - Specification that as a result has a specification of what you want to implement and you clearly specify which limitations of native multisig will be improved Milestone 2 - PoC

Thanks for your contribution and comments. We thought about splitting this phase into two, but we decided to go over the concept of "built to discover" instead of discover to build! Nonetheless, we will provide two deliverables: a specification document and a PoC feasibility. We don't find a precise point in splitting, but we may be missing something.

2023-05-15 19:20 UTC, mike1729 commented
The precise point in splinting is that with products based on cryptography there is no space for trial and error. You produce a specification and implement it.

2023-05-15 20:02 UTC, 0xLucca commented
Hi @mike1729! We value your input and agree with the emphasis on clarity, especially when discussing cryptographic elements. Our smart contract project isn't designed to create new cryptographic systems but to leverage the existing ones within the Polkadot ecosystem.
The proposed multisig wallet, while not directly implementing new cryptographic techniques, relies on cryptographic operations provided by Polkadot for secure transaction signing and execution. In essence, the smart contract will manage multisig operations using the state of the contract, tracking approvals and executing transactions once a set threshold is met.
This process leans on the digital signatures generated by wallet owners, which are intrinsically tied to Polkadot's cryptographic infrastructure. While we're not building low-level cryptographic operations, our design depends on the cryptographic principles and mechanisms embedded in the Polkadot network for secure and validated transactions.
We apologize for any misunderstanding our initial descriptions may have caused, and we're grateful for your patience as we refine our explanations. In future communications, we commit to further enhancing our accuracy. Thank you for your constructive feedback and understanding.

2023-05-15 21:04 UTC, 0xMarkian commented
Hey ! thanks for the application, could you indicate chosen category?

2023-05-16 12:12 UTC, GabrielCamba commented
> Hey ! thanks for the application, could you indicate chosen category?

Hi @0xMarkian, Sorry we didnt' add the category. Our project fits in the "Infrastructure" category.

Our project aims to build a multisig wallet using ink! that can interact with the Contract Pallet on any substrate chain, along with a user-friendly interface, it enhances the Polkadot/ink! ecosystem's developer infrastructure and tooling. This multisig wallet could also facilitate the creation of DAOs and enable individuals to securely manage cryptocurrency assets, which could be seen as an aspect of DAO tooling.

2023-05-16 16:19 UTC, 0xMarkian approved these changes
Hey, thanks for the application. I am approving

2023-05-22 12:00 UTC, 0xLucca commented
> Hi @mike1729! We value your input and agree with the emphasis on clarity, especially when discussing cryptographic elements. Our smart contract project isn't designed to create new cryptographic systems but to leverage the existing ones within the Polkadot ecosystem. The proposed multisig wallet, while not directly implementing new cryptographic techniques, relies on cryptographic operations provided by Polkadot for secure transaction signing and execution. In essence, the smart contract will manage multisig operations using the state of the contract, tracking approvals and executing transactions once a set threshold is met. This process leans on the digital signatures generated by wallet owners, which are intrinsically tied to Polkadot's cryptographic infrastructure. While we're not building low-level cryptographic operations, our design depends on the cryptographic principles and mechanisms embedded in the Polkadot network for secure and validated transactions. We apologize for any misunderstanding our initial descriptions may have caused, and we're grateful for your patience as we refine our explanations. In future communications, we commit to further enhancing our accuracy. Thank you for your constructive feedback and understanding.

Hi @mike1729! I hope you're doing well. I wanted to follow up on the message we sent regarding the proposed multisig design. We would like to ensure that your doubts and questions are properly addressed.

If you have any remaining doubts or if there is any specific aspect you would like us to clarify further, please let us know.

2023-05-23 11:10 UTC, mike1729 approved these changes
I approve but I believe that it would be better to first produce a specification. However, the risk is yours if you want to produce both specification and proof-of-concept implementation at the same time.

Regarding cryptographic tools you'll use, I know that you will use existing infrastructure in substrate and ink to ensure correctness of operations but at the same time you'll introduce new cryptographic operations that should be a subject of detail design and the implementation should be a subject of code audit.

2023-05-23 11:44 UTC, TtomaS7 commented
Congratulations! We are thrilled to officially welcome you to the Ink!ubator program!! We can't wait to see the remarkable contributions you'll bring to the ecosystem.
In terms of the next steps, we are eagerly anticipating your first delivery, which is due in 4 weeks. When it’s ready, please create a PR here - https://github.com/use-inkubator/Grant-Milestone-Delivery

If you have any questions, concerns, or if you just want to brainstorm ideas, don't hesitate to reach out. We encourage you to utilize our Element channel for any inquiries - https://matrix.to/#/#sm-bounty-support:matrix.org

As you join the Ink!ubator family, please remember that you are not alone on this journey. We are here to support you every step of the way. We believe in your potential and we can't wait to see where this journey takes us all.

Congratulations once again and welcome aboard!

2023-05-23 11:44 UTC, merged

2023-05-23 17:33 UTC, DiegoTorresborda commented
> Congratulations! We are thrilled to officially welcome you to the Ink!ubator program!! We can't wait to see the remarkable contributions you'll bring to the ecosystem. In terms of the next steps, we are eagerly anticipating your first delivery, which is due in 4 weeks. When it’s ready, please create a PR here - https://github.com/use-inkubator/Grant-Milestone-Delivery
> 
> If you have any questions, concerns, or if you just want to brainstorm ideas, don't hesitate to reach out. We encourage you to utilize our Element channel for any inquiries - https://matrix.to/#/#sm-bounty-support:matrix.org
> 
> As you join the Ink!ubator family, please remember that you are not alone on this journey. We are here to support you every step of the way. We believe in your potential and we can't wait to see where this journey takes us all.
> 
> Congratulations once again and welcome aboard!

Thank you for welcoming Protofire to the Ink!ubator program and entrusting us with this project. We are incredibly grateful for the opportunity to contribute to the ecosystem. It’s truly exciting for us!
Although one of our developers is on holiday until the end of this week, we are committed to starting work immediately. We appreciate your understanding in this matter.
Once again, we want to express our gratitude for your trust and support. We eagerly look forward to collaborating with you and ensuring the success of this project.